version: "3.8"

services:
  app:
    build:
      context: ./backend
    container_name: alibar-laravel
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www
    working_dir: /var/www
    command: php artisan serve --host=0.0.0.0 --port=8000
    restart: unless-stopped

  node:
    build:
      context: ./frontend
    container_name: alibar-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app
    command: npm run dev -- --host
    restart: unless-stopped

volumes:
  dbdata:
    driver: local
